### ISSUE TITLE
v-for 和 v-if 在同一个标签下会报错

### ISSUE THREAD

**Issue by aruiplex** [yiluyanxia/vue-todolist#1]
- 报错位置: 
@/views/Home.vue, 14和24行
- 报错: 
[vue/no-use-v-if-with-v-for]
The 'todoList' variable inside 'v-for' directive should be replaced with a computed property that returns filtered array instead. You should not mix 'v-for' with 'v-if'.

- 我是初学者, 多谢帮助

**Comment by Rachel24601** [comment]
确实是这样， 'v-for' 和 'v-if' 不能混用，需要分开写，比如这样：
`            <ol class="demo-box" v-for="(item, index) in todoList" :key="index">
                <li v-if="item.done === false">
                    <input type="checkbox" @change="changeTodo(index, true)">
                    <p>{{item.todo}}</p>
                    <a @click="deleteTodo(index, true)">-</a>
                </li>
            </ol>`

**Comment by Rachel24601** [comment]
'v-for' 和 'v-if' 不能混用，需要分开写，比如这样：

            <ol class="demo-box" v-for="(item, index) in todoList" :key="index">
                <li v-if="item.done === false">
                    <input type="checkbox" @change="changeTodo(index, true)">
                    <p>{{item.todo}}</p>
                    <a @click="deleteTodo(index, true)">-</a>
                </li>
            </ol>
